In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a


array([1, 2, 3])

In [3]:
a.ndim

1

In [6]:
a.shape

(3,)

In [7]:
a = np.array([[1,2,3,4]])
a

array([[1, 2, 3, 4]])

In [8]:
a.ndim

2

In [9]:
a.shape

(1, 4)

In [10]:
a.reshape(2,2)
(a)

array([[1, 2, 3, 4]])

In [11]:
a = np.array([[[1,2,3],[2,3,4],[4,5,6]]])
a

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]])

## arange

In [12]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a.ndim

1

In [14]:
a.shape

(9,)

## linespace

In [18]:
a = np.linspace(1,10,5,dtype=int)
a

array([ 1,  3,  5,  7, 10])

## zeros

In [20]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

## ones

In [21]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

# converting dimensions

In [22]:
a = np.arange(1,51)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [23]:
# 1d to 2d

In [25]:
b = a.reshape(10,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [30]:
b = a.reshape(5,2,5)
b

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]]])

In [32]:
b.ndim

3

In [34]:
c = np.sum(b)
c

1275

In [36]:
a = np.arange(1,50)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [38]:
b = np.sum(a)
b

1225

In [47]:
a = np.arange(1,61)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [48]:
b = a.reshape(10,6)
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [50]:
b = np.arange(1,50)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [52]:
c = b.reshape(7,7)
c


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [53]:
d = np.sum(c,axis = 1)
d
    

array([ 28,  77, 126, 175, 224, 273, 322])

In [55]:
a = np.arange(1,61).reshape(10,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [64]:
b = np.arange(60,120).reshape(10,6)
b

array([[ 60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77],
       [ 78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101],
       [102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119]])

In [65]:
c = np.vstack((a,b))
print(c)

[[  1   2   3   4   5   6]
 [  7   8   9  10  11  12]
 [ 13  14  15  16  17  18]
 [ 19  20  21  22  23  24]
 [ 25  26  27  28  29  30]
 [ 31  32  33  34  35  36]
 [ 37  38  39  40  41  42]
 [ 43  44  45  46  47  48]
 [ 49  50  51  52  53  54]
 [ 55  56  57  58  59  60]
 [ 60  61  62  63  64  65]
 [ 66  67  68  69  70  71]
 [ 72  73  74  75  76  77]
 [ 78  79  80  81  82  83]
 [ 84  85  86  87  88  89]
 [ 90  91  92  93  94  95]
 [ 96  97  98  99 100 101]
 [102 103 104 105 106 107]
 [108 109 110 111 112 113]
 [114 115 116 117 118 119]]


In [66]:
c. T

array([[  1,   7,  13,  19,  25,  31,  37,  43,  49,  55,  60,  66,  72,
         78,  84,  90,  96, 102, 108, 114],
       [  2,   8,  14,  20,  26,  32,  38,  44,  50,  56,  61,  67,  73,
         79,  85,  91,  97, 103, 109, 115],
       [  3,   9,  15,  21,  27,  33,  39,  45,  51,  57,  62,  68,  74,
         80,  86,  92,  98, 104, 110, 116],
       [  4,  10,  16,  22,  28,  34,  40,  46,  52,  58,  63,  69,  75,
         81,  87,  93,  99, 105, 111, 117],
       [  5,  11,  17,  23,  29,  35,  41,  47,  53,  59,  64,  70,  76,
         82,  88,  94, 100, 106, 112, 118],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  65,  71,  77,
         83,  89,  95, 101, 107, 113, 119]])

In [69]:
a = np.arange(1,61).reshape(10,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [71]:
a[1:2,3:5]

array([[10, 11]])

In [72]:
a[0:1,0:1]

array([[1]])

In [73]:
import math

In [75]:
math.gamma(8)

5040.0

In [ ]:
a = 