In [2]:
a = [1,2,3,4,5,6,7,8,9]
b = list(map(lambda x:x+2,a))
b

[3, 4, 5, 6, 7, 8, 9, 10, 11]

In [7]:
print('\\n')

\n


In [12]:
a= [1,5,7,8,9]
list(map(lambda x:x>2,a))

[False, True, True, True, True]

In [11]:
a= [1,5,7,8,9]
list(filter(lambda x:x>2,a))

[5, 7, 8, 9]

In [13]:
a = [1,2,3,4,5]
b = map(lambda x:x+3,filter(lambda x:x>3,a))
print(list(b))

[7, 8]


In [16]:
a  = [1,2,3,4,5]
b = filter(lambda x:x%2==0,map(lambda x:x+3,a))
print(list(b))

[4, 6, 8]


In [17]:
import numpy as np

In [28]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [31]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [33]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [42]:
import pandas as pd

In [53]:
a= np.arange(1,61).reshape(10,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [54]:
b = pd.DataFrame(a)
b

0   1   2   3   4   5
0   1   2   3   4   5   6
1   7   8   9  10  11  12
2  13  14  15  16  17  18
3  19  20  21  22  23  24
4  25  26  27  28  29  30
5  31  32  33  34  35  36
6  37  38  39  40  41  42
7  43  44  45  46  47  48
8  49  50  51  52  53  54
9  55  56  57  58  59  60

In [48]:
a = pd.Series([1,5,6,7,8,9])
a

0    1
1    5
2    6
3    7
4    8
5    9
dtype: int64

In [55]:
v= pd.read_csv('./titanic_data.csv')
v

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [62]:
v.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [64]:
v.size

10692

In [65]:
v.shape

(891, 12)

In [72]:
a= np.arange(1,21).reshape(5,4)
b = pd.DataFrame(a)
b

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20

In [77]:
b.loc[1:2][2:3]

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [79]:
a = np.arange(1,21).reshape(5,4)
b = pd.DataFrame(a)
b

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20

In [82]:
b.loc[0:3][1]

0     2
1     6
2    10
3    14
Name: 1, dtype: int32

In [84]:
b.iloc[0:3][0]

0    1
1    5
2    9
Name: 0, dtype: int32

In [3]:
a = [1,2,3,4,5,6,7,8,9]
b = list(map(lambda x:x>4,a))
b

[False, False, False, False, True, True, True, True, True]

In [4]:
a = [1,2,3,4,5,6,7,8,9]
b = list(filter(lambda x:x>4,a))
b

[5, 6, 7, 8, 9]

In [11]:
from functools import reduce

In [13]:

b = reduce(lambda x,y :x+y,[1,2,3,4])
b

10

# list comprehension

In [15]:

a = [i for i in range(1,10) if i%2==0]
a

[2, 4, 6, 8]

In [17]:
a= [ 'even' if i%2==0 else 'odd' for i in range(1,4)]
a

['odd', 'even', 'odd']

# dictiojary comprehewnsion

In [20]:
a = {i:i**2 for i in range (1,5)}
a

{1: 1, 2: 4, 3: 9, 4: 16}

# file handling

In [21]:
import numpy as np

In [24]:
a = np.array([[1,2,4]])
print(a)
a.ndim

[[1 2 4]]


2

In [26]:
a= np.array([[1,2,3],[4,6,7]])
a

array([[1, 2, 3],
       [4, 6, 7]])

In [27]:
a= np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a = np.linspace(10,20,10,dtype=int)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20])

In [35]:
a= np.zeros((3,3),dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [42]:
a = np.arange(1,61).reshape(10,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [39]:
a[1][1][1]

20

In [43]:

c = np.sum(a,axis=1)
c

array([ 21,  57,  93, 129, 165, 201, 237, 273, 309, 345])

In [48]:
a = np.arange(1,61).reshape(10,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [49]:
b = np.arange(101,161).reshape(10,6)
b

array([[101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118],
       [119, 120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136],
       [137, 138, 139, 140, 141, 142],
       [143, 144, 145, 146, 147, 148],
       [149, 150, 151, 152, 153, 154],
       [155, 156, 157, 158, 159, 160]])

In [51]:
c = np.hstack((a,b))
c

array([[  1,   2,   3,   4,   5,   6, 101, 102, 103, 104, 105, 106],
       [  7,   8,   9,  10,  11,  12, 107, 108, 109, 110, 111, 112],
       [ 13,  14,  15,  16,  17,  18, 113, 114, 115, 116, 117, 118],
       [ 19,  20,  21,  22,  23,  24, 119, 120, 121, 122, 123, 124],
       [ 25,  26,  27,  28,  29,  30, 125, 126, 127, 128, 129, 130],
       [ 31,  32,  33,  34,  35,  36, 131, 132, 133, 134, 135, 136],
       [ 37,  38,  39,  40,  41,  42, 137, 138, 139, 140, 141, 142],
       [ 43,  44,  45,  46,  47,  48, 143, 144, 145, 146, 147, 148],
       [ 49,  50,  51,  52,  53,  54, 149, 150, 151, 152, 153, 154],
       [ 55,  56,  57,  58,  59,  60, 155, 156, 157, 158, 159, 160]])

In [52]:
# diagonal
a = np.diag([1,2,3,40])
a

array([[ 1,  0,  0,  0],
       [ 0,  2,  0,  0],
       [ 0,  0,  3,  0],
       [ 0,  0,  0, 40]])

In [53]:
a = np.array([[1,2,3,4],[20,30,40,50]])
a.T

array([[ 1, 20],
       [ 2, 30],
       [ 3, 40],
       [ 4, 50]])

In [54]:
# concatenate

In [2]:
a= 'vinay'
b = list(a)
b

['v', 'i', 'n', 'a', 'y']

In [3]:
a = ' have a good day'
a.split()

['have', 'a', 'good', 'day']

In [6]:
''.join(a)

' have a good day'

In [8]:
a = 'data science'
a.count('a')

2

In [12]:
a = 'data .science. is. a .very. good .job'
b = a.split('.')
c = a.split('.',5)
c


['data ', 'science', ' is', ' a ', 'very', ' good .job']

In [15]:
a = ' my name is {}'.format('vinay')
a

' my name is vinay'

In [19]:
a = ['vinay']
b = a.copy()
b

['vinay']

In [21]:
a = [1,23,56,78]
a.insert(2,100)
a

[1, 23, 100, 56, 78]

In [25]:
a.pop()
print(a)

[1, 100]


In [32]:
a = [1,2,3,4,5]
a.pop(1)
print(a)

[1, 3, 4, 5]


In [30]:
a.pop()

5

In [42]:
a = [1,2,3,4,4,8]

In [43]:
a.count(4)


2

In [45]:
a.sort()
a

[1, 2, 3, 4, 4, 8]

In [48]:
a.sort(reverse=True)
a

[8, 4, 4, 3, 2, 1]

In [49]:
a = [1,2,3,4,4,8]
b = [ 4,7,8,9,0]
c = a+b
c

[1, 2, 3, 4, 4, 8, 4, 7, 8, 9, 0]

In [52]:
a = ('vinay','ravi','kiran')
(name,friend,close)=a
print(name)

vinay


In [55]:
a =set()
type(a)

set

In [58]:
a.add(9)
a

{9}

In [60]:
a.update([9,12])
a

{9, 12}

In [65]:
a = {0,9,8,7,7,7,4}
a.update([90])
a

{0, 4, 7, 8, 9, 90}

In [71]:
a.discard(767)
a

{0, 4, 7, 8, 9}

In [73]:
a.remove(77)
a

KeyError: 77

# functiones

In [91]:
def kumar(a):
    if a%2==0:
        print('even')
    else:
        print('odd')

In [92]:
kumar(90)

even


In [97]:
c = []
for i in range(10):
    a = int(input())
    c.append(a)
print(c)

55
566
77
88
77
77
55
44
44
4
[55, 566, 77, 88, 77, 77, 55, 44, 44, 4]


In [111]:
def vinay(a,b):
    print(a+b)
    

In [112]:
vinay(12,45)

57


TypeError: kamal() takes 0 positional arguments but 2 were given

In [1]:
print('vk')

vk


In [4]:
a = 100
b = 5
print(a/b)

20.0


In [1]:
a = int('4')
(a)
            

4

In [23]:
a = int(input())
if a%3==0 and a%5==0:
    print('fizz','buzz')
elif  a%5==0:
    print('buzz')
    
elif a%3==0:
     print('fizz')




30
fizz buzz


In [5]:
# prime number

a = int(input())
count= 0
for i in range(1,a+1):
    if a%i==0:
        count= count+1
if count==2:
    print(i,'prime number')
else:
    print(i,'not a prime number')


KeyboardInterrupt: Interrupted by user

In [7]:
153%10


3

In [8]:
153//10

15

In [ ]:
# factorial
a = int(input())
sum=0
while a>0:
    sum= a%10

In [18]:
a=12
print(a)

12


In [19]:
c=54
type(c)

int

In [20]:
# i am a data scientist

In [25]:
import numpy


In [24]:
145%10

5

In [23]:
145//10

14

In [35]:
a= input()
if a == a[::-1]:
    print('its a palindrome')
else:
    print('not a palindrome')

        
        
    

vnay
not a palindrome


In [17]:
for i in range(1,101):
    count=0
    for j in range(1,1+i):
        if i%j==0:
            count= count+1
    if count==2:
        print(i,end=' ')

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

In [16]:
n = int(input())
count=0
for i in range(1,n+1):
    if n%i==0:
        count= count+1
if count==2:
    print(n,'prime')
else:
    print(n,'not a prime')

9
9 not a prime


# i am vinay 

In [21]:
# 12 integer [int]
# 12.5 float[float]
# vinay strings[str]

In [31]:
a='kamal'
print(a)

kamal


In [23]:
# first of all i am going to learn about syntax 
#  print condition 
#  [] square bracket 
#  {} flower bracket 
#  () paranthesis 


In [24]:
# print condition 
print ('kiran')

kiran


# data types and vareiables 

In [4]:
a = int(input())
count=0
for i in range(1,a+1):
    if a%i==0:
        count=count+1
if count==2:
    print(i,'prime')
else:
    print(i,'not a prime')

7
7 prime


In [12]:
a = input() #vinay
f = {}
b = 0
for i in a:
    count=0
    for j in a:
        if i==j:
            count=count+1
    f[i]=count
print(f)

    
    


vinaykumar
{'v': 1, 'i': 1, 'n': 1, 'a': 2, 'y': 1, 'k': 1, 'u': 1, 'm': 1, 'r': 1}


In [33]:
a = []

for i in range(5):
    a.append(int(input()))
print(a)
k = 0
for j in a:
    k = k+j
print(k)
c = k / len(a)
print(c)


1
2
3
4
5
[1, 2, 3, 4, 5]
15
3.0


In [56]:
a = input()  
b = a[::-1]
if a ==b:
    print('ok')
else:
    print('not ok')

    


noon
ok


In [43]:
a = int(input())
k = 0
while a>0:
    l = a%10
    k =  k+l
    a = a//10
print(k)
    
    

123
6


In [36]:
# given integer in reverse manner
a = int(input())
b = str(a)
print(int(b[::-1]))

1234
4321


## b = int(input())
h = int(input())
c = 1/2*(b*h)
print(c)

In [8]:
a = int(input())
if a%2==0:
    print('even')
else:
    print('odd')

19
odd


In [7]:
a  = 3
b  = 5
c  = a+b
print(c)
print()
print(type(c))

8

<class 'int'>


In [5]:
a = int(input())
b = 1
for i in range(1,a+1):
    b=b*i
print(b)
    

5
120


In [25]:
# 12=integer (int)
# 15.5=float (float)
# vinay=strings (str)

In [26]:
# a=12
# here a is variable and 12 is variable value 
#

In [27]:
c='siva'
type(c)

str

In [28]:
a=12
print(a)

12


In [29]:
c='vinay'
print(c)

vinay


# i am a learner 

In [1]:
# markdown is for headings 
# raw NBconvert is for normal line 

In [1]:
# syntax 
[]
{}
()


()

In [2]:
a = 12
print(a)
print()
type(a)

12



int

In [3]:
# variable values
# variable cannot start with a number 
# no white space in varaible names 
# use _instead 
# variable names are case sensotive 
# cabt use below symbols 


In [4]:
# integer and float converts into strings but a string cannot convert into integer or float  

In [5]:
# if it is text it wont convert if it is name it will conevrt 

# complete print condition 

In [6]:
#  first technique = ,

In [7]:
# second techique=  +  (it can only convert  strings)


In [8]:
# third technique = using d types 

In [1]:
# ing

In [2]:
sai_kamal=12
print(sai_kamal)

12


In [4]:
a = 12
print(a)
print()
print(type(a))

12

<class 'int'>


In [5]:
a = 12
b = float(a)
print(b)

12.0


In [6]:
a = 12.5
b = int(a)
print(a)
print()
print(b)

12.5

12


In [8]:
a =24 
b = str(a)
print(a)
print()
b

24



'24'

In [9]:
# complete print condition

In [11]:
# first techinque using ,

# i am viany my age is 25
a = 'vinay'
b = 25
print('i am ',a,'my age is',b)

i am  vinay my age is 25


In [14]:
# second technique using +
# my name is vinay and my age is 25
a = '25'
print('my name is vinay and my age is '+a)



my name is vinay and my age is 25


In [22]:
a = 'vinay'
b = '25'
print('my name is ' +a+  ' and my age is ' +b)

my name is vinay and my age is 25


In [23]:
# third techinques using d types

In [24]:
# int= %d
# float=%f
# string=%s

In [25]:
# my name is siva i am 25
a = 'siva'
b = 25
print('my name is %s i am %d'%(a,b))


my name is siva i am 25


In [28]:
print('siva\nkamal')

siva
kamal


In [29]:
print('siva\tkamal')

siva	kamal


In [30]:
# strings 
a = 'vinay'
print(a[2])

n


In [33]:
print(""" dhfldskfjhkf
fvdsfhdsjkfsd
jhgfjdsfhsdjfcn
jfbdsjfhdasjf'
 """)

 dhfldskfjhkf
fvdsfhdsjkfsd
jhgfjdsfhsdjfcn
jfbdsjfhdasjf'
 


In [35]:
a = 'vinaykumar'      # n-1
print(a[0:5]) 

vinay


In [36]:
print(a[0:5:3])

va


In [38]:
 print(a[:])

vinaykumar


In [41]:
ord('f')

102

In [42]:
chr(103)

'g'

In [1]:
#  online class string

# predefined functions or in built functions 

In [117]:
# while loop
x = 1
while x<=10:
    print(x)
    x= x+1

1
2
3
4
5
6
7
8
9
10


In [118]:
# break
for i in range(1,11):
    print(i)
    if i==6:
        break

1
2
3
4
5
6


In [122]:
for i in range(1,11):
    if i==4:
        continue
    print(i,end ='* ')

1* 2* 3* 5* 6* 7* 8* 9* 10* 

In [124]:
a = 10
b = 20
print(f'value of a is {a}and value {b}')

value of a is 10and value 20


In [114]:
x = ['vinay','siva','murali']
y = ['venu','ink','link']
c = zip(x,y)
print(list(c))

[('vinay', 'venu'), ('siva', 'ink'), ('murali', 'link')]


In [115]:
a = [100,200,300,400]
for i,j in enumerate(a):
    print(i,j)

0 100
1 200
2 300
3 400


In [2]:
# 
a = 'data science'
a.capitalize()

'Data science'

TypeError: count() takes at least 1 argument (0 given)

 # pre defined function

In [1]:
# capitalize 
# count 
# endswith
# isalnum
# isalpha
# isdecimal
# isdigit
# islower
# isupper
# upper 
# title
# replace
# startswith
# swapcase

In [2]:
# 
a = 'swetha'
a.capitalize()

'Swetha'

In [6]:

a = 'vinay'
a.count('i')

1

In [7]:

a = 'siva'
a.startswith('s')

True

In [9]:
a = 'vinay'
a. endswith('y')

True

In [11]:
a = '324322'
a.count('2')

3

In [12]:
a = 'raja'
a.isalpha()

True

In [13]:
a = "vinay123"
a.isalpha()

False

In [15]:
a = '576756'
a.isdigit()

True

In [16]:
# no space should taken in middle

In [18]:
a = 'ramesh'
a.isalnum()

True

In [19]:
a = 'siva'
a.isalnum()

True

In [20]:
a = 'raMESH'
a.lower()

'ramesh'

In [22]:
a = 'rakHi'
a.upper()

'RAKHI'

In [23]:
a = 'swapna'
a.isupper()

False

In [27]:
a = 'raVi'
a.isupper()

False

In [28]:
a = 'i am viany and my age is 25'
a.title()

'I Am Viany And My Age Is 25'

In [31]:
# replace
d = 'i am learning machine learning and data learning'
d.replace('and','viany')

'i am learning machine learning viany data learning'

In [32]:
# formating technique


In [39]:
d = 'this is viany'
print('this is {}'.format('viany'))

this is viany


In [2]:
print('i am learning {a}','and {b}') .format(a= 'vinay',b= 'siva')

i am learning {a} and {b}


AttributeError: 'NoneType' object has no attribute 'format'

In [3]:
print('i am learning {s}'.format(s,'siva'))

NameError: name 's' is not defined

In [12]:
print('siva and viany are {}'.format('bestfriends'))

siva and viany are bestfriends


In [15]:
# using ,
a= 'vinay'
b ='siva'
c = 'kiran'
print(a,b,c,'are friends')

vinay siva kiran are friends


# list

In [17]:
# list is mutable data strctures
# it is denoted with -[]
# it will accept any data type 
# if a string is in the () we cant change but if a string is in the [] we can change

In [18]:
a =[12,13.4,'datascience']
print(a)

[12, 13.4, 'datascience']


In [19]:
type(a)

list

In [27]:
for i in a:
    print(i)
    print(type(i))
  

12
<class 'int'>
13.4
<class 'float'>
datascience
<class 'str'>


In [30]:
a = 'rwvo'
(a)

'rwvo'

In [32]:
## index and slicing 
b = [12,232,'siva','rabo','kamal']
(b[3])

'rabo'

In [49]:
a = ['vinay',12,12.5]
a.append(5)
(a)

['vinay', 12, 12.5, 5]

In [51]:
a = ['siva',12232,34.5,'4356']
a.clear()
(a)

[]

In [54]:
a = [841,3.71,'sivasankar']
b=a.copy()
(a)

[841, 3.71, 'sivasankar']

In [27]:
a =[1,13,34,'datascience',1,1]
a.count(1)


3

In [56]:
a = ['dbsadb',12,12.5,'vinay']
b = [11,'dfaef',23.4]
a.extend(b)
(a)

['dbsadb', 12, 12.5, 'vinay', 11, 'dfaef', 23.4]

In [58]:
a = ['gdfhfhg',12,12.5,"dgffsrf"]
a.index(12)



1

In [60]:
a = ['dfwf',12,34.5]
a.insert(1,55)
(a)

['dfwf', 55, 12, 34.5]

In [39]:
a = ['dfds',33,33.5,]
a.pop()
(a)

['dfds', 33]

In [63]:
a = ['siva','rajitha',78,78.8]
a.pop(1)

'rajitha'

In [72]:
a = ['begum','divya',33,]
a.remove(33)
(a)

['begum', 'divya']

In [74]:
a = ['divya',33,89.0]
a.reverse()
(a)

[89.0, 33, 'divya']

In [77]:
a = [44,12,33.5]
a.sort()
(a)

[12, 33.5, 44]

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (3995207800.py, line 1)

In [83]:
a = ['siva',23,44.5]
a.index(23)


1

In [87]:
a = ['dbfj',44,66.7]
a.pop()

66.7

In [88]:
a.pop()

44

In [1]:
a = ['rgterfe','rtewrew','hgfhfh',]

a.pop(1)

'rtewrew'

# tuple

In [2]:
# tuple
a = (10)
(type(a))

int

In [3]:
a = (10,)
(type(a))

tuple

In [5]:
a = (4,10,13,'siva','ravi',12.4)
(a[1])

10

In [10]:
a = (12,[12,32],'vinay','siva')
(a[1][1])

32

In [11]:
# tuple is mutable

In [12]:
a = ('vinay','siva',23,45.5)
a[1]='rama'

TypeError: 'tuple' object does not support item assignment

In [13]:
# packing and packing content

In [16]:
a = ('vinay','degreee',2022)
(name,study,lunch)  = a
(name)

'vinay'

In [17]:
(lunch)

2022

In [24]:
a= (23,'vinay','dogs')
(age,siva,divya) = a
(siva)

'vinay'

In [28]:
# operators
a =( 2,3,4)
b = (12.5,34)
(a+b)

(2, 3, 4, 12.5, 34)

In [32]:
a = (45,5)
b = a*6
(b)


(45, 5, 45, 5, 45, 5, 45, 5, 45, 5, 45, 5)

In [34]:
# member ship function
a = (1,44,'python')
(13 in a)

False

In [35]:
(1 in a)

True

In [47]:
a = (1,23,43,54,65)
for i in a:
    print(i)
    (i)
    

1
23
43
54
65


In [48]:
# built in functions

a = (23,'siva')
a.index(23)

0

In [49]:
a.count('siva')

1

In [50]:
len(a)

2

In [52]:
a = (12,44,544,67,67666,66)
max(a)

67666

In [53]:
min(a)

12

In [54]:
len(a)

6

In [55]:
a = 23,45,76b 
max(a)

76

In [56]:
len(a)

3

In [58]:
#sort
a =(34,23,45,65,12)
sorted(a)

[12, 23, 34, 45, 65]

In [59]:
## string concept split
a = 'vinay is studying inabroad'
a.split()

['vinay', 'is', 'studying', 'inabroad']

# join

In [63]:
a = 'dogs eat cat'
b = a.split()
(b)


['dogs', 'eat', 'cat']

In [65]:
d = ' '.join(b)

In [70]:
a = 'i am happy'
b =a.split()
d = ' '.join(b)
(d)


'i am happy'

In [1]:
# stirngs
a = '1,2,3,4,5'
(a)

'1,2,3,4,5'

In [2]:
(type(a))

str

In [3]:
(a[0:2])

'1,'

In [1]:
# rough list 
a = [1,2,34,5,6,6]
a[0]=34
(a)


[34, 2, 34, 5, 6, 6]

In [3]:
a = [('siva'),45,78,98,1]
a[0]=19
(a)
      

[19, 45, 78, 98, 1]

In [4]:
(a[0])

19

In [5]:
max(a)

98

In [7]:
len(a)

5

In [8]:
sum(a)

241

In [17]:
a =[1,2,4,2]
a.append(88)
(a)

[1, 2, 4, 2, 88]

In [20]:
a =[1,2,3,4,5,6]
a.insert(2,3)
(a)

[1, 2, 3, 3, 4, 5, 6]

In [22]:
a.extend([12,100])
(a)

[1, 2, 3, 3, 4, 5, 6, 12, 100, 12, 100]

In [23]:
a = [12,34,56,788]
a.extend([10,100])
(a)

[12, 34, 56, 788, 10, 100]

In [26]:
a= 'pinky'
(a)

'pinky'

In [28]:
a = [1,2,3,4,5]
b = [0,9,8,7,6]
c = a+b
(c)

[1, 2, 3, 4, 5, 0, 9, 8, 7, 6]

In [31]:
a = [1,'siva','pinky']
del a[1]
(a)

[1, 'pinky']

In [35]:
a = [1,'siva','pinky']
a.remove(1)
(a)

['siva', 'pinky']

In [38]:
a = [1,'siva','pinky']
a.pop()

'pinky'

In [37]:
a = [1,'siva','pinky']
a.pop(1)

'siva'

In [40]:
a = [1,'siva','pinky']
a.clear()
(a)

[]

In [43]:
a = 'siva',89
b=list(a)
(b)

['siva', 89]

In [51]:
a = [1,4,5,6,3,54,88]
(sorted(a))

[1, 3, 4, 5, 6, 54, 88]

In [60]:
a = [1,4,5,6,3,54,88]
a.sort(reverse=True)
print(a)

[88, 54, 6, 5, 4, 3, 1]


In [61]:
# index and count and remove we use what is there in the index
a = [1,4,5,6,3,54,88]
a.reverse()
(a)

[88, 54, 3, 6, 5, 4, 1]

In [2]:
 # tuple
a = 1,2,3,4
(type(a))

tuple

In [3]:
a = 1,2,3,(12,34),[12,34]
(type(a))

tuple

In [4]:
a = (1,2,3,(12,34),[34,65],'stirng')
(a[0])

1

In [9]:
(a[3])

(12, 34)

In [13]:

(a[0])

1

In [15]:
a = 'viany'
(a[1])

'i'

In [16]:
a = 12,34,453,32,2,3,2,34,2,3
a.index(34)

1

In [10]:
#  split
a = 'i am a goood boy'
print(a.split())

['i', 'am', 'a', 'goood', 'boy']


In [11]:
b = 'kgf is rocky bhai world'
b.split()

['kgf', 'is', 'rocky', 'bhai', 'world']

In [13]:
[''.join(b)]

['kgf is rocky bhai world']

In [14]:
a = 'my name is vinay'
a.split()

['my', 'name', 'is', 'vinay']

In [19]:
[''.join(a)]

['my name is vinay']

In [20]:
a = 'i am a good boy in the class '
a.split()

['i', 'am', 'a', 'good', 'boy', 'in', 'the', 'class']

In [21]:
[''.join(a)]

['i am a good boy in the class ']

In [22]:
a = 'vinay'
a.capitalize()

'Vinay'

In [23]:
a.casefold()

'vinay'

In [30]:
a.count('i')

2

In [31]:
a = 'i am big fan of rocky'
a.title()

'I Am Big Fan Of Rocky'

In [32]:
a.replace('am','we')

'i we big fan of rocky'

In [46]:
for i in range(1,23):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22


In [47]:
a = 'datascience'
for i in a:
    print(i)

d
a
t
a
s
c
i
e
n
c
e


In [48]:
Jupyter Notebook
rough
Last Checkpoint: 08/11/2022
(unsaved changes)
Current Kernel Logo
Python 3 (ipykernel) 
File
Edit
View
Insert
Cell
Kernel
Widgets
Help

Code
print('vk')
vk
a=12
print(a)
12
c=54
type(c)
int
# i am a data scientist
i am good boy
i am vinay
# 12 integer [int]
# 12.5 float[float]
# vinay strings[str]
a='kamal'
print(a)
kamal
# first of all i am going to learn about syntax 
#  print condition 
#  [] square bracket 
#  {} flower bracket 
#  () paranthesis 
​
# print condition 
print ('kiran')
kiran
data types and vareiables
# 12=integer (int)
# 15.5=float (float)
# vinay=strings (str)
# a=12
# here a is variable and 12 is variable value 
#
c='siva'
type(c)
str
a=12
print(a)
12
c='vinay'
print(c)
vinay
i am a learner
now i am learning 
# markdown is for headings 
# raw NBconvert is for normal line 
# syntax 
[]
{}
()
​
()
a = 12
print(a)
print()
type(a)
12

int
# variable values
# variable cannot start with a number 
# no white space in varaible names 
# use _instead 
# variable names are case sensotive 
# cabt use below symbols 
​
# integer and float converts into strings but a string cannot convert into integer or float  
# if it is text it wont convert if it is name it will conevrt 
complete print condition
#  first technique = ,
# second techique=  +  (it can only convert  strings)
​
# third technique = using d types 
# ing
sai_kamal=12
print(sai_kamal)
12
a = 12
print(a)
print()
print(type(a))
12

<class 'int'>
a = 12
b = float(a)
print(b)
12.0
a = 12.5
b = int(a)
print(a)
print()
print(b)
12.5

12
a =24 
b = str(a)
print(a)
print()
b
24

'24'
# complete print condition
# first techinque using ,
​
# i am viany my age is 25
a = 'vinay'
b = 25
print('i am ',a,'my age is',b)
i am  vinay my age is 25
# second technique using +
# my name is vinay and my age is 25
a = '25'
print('my name is vinay and my age is '+a)
​
​
my name is vinay and my age is 25
a = 'vinay'
b = '25'
print('my name is ' +a+  ' and my age is ' +b)
my name is vinay and my age is 25
# third techinques using d types
# int= %d
# float=%f
# string=%s
# my name is siva i am 25
a = 'siva'
b = 25
print('my name is %s i am %d'%(a,b))
​
my name is siva i am 25
print('siva\nkamal')
siva
kamal
print('siva\tkamal')
siva	kamal
# strings 
a = 'vinay'
print(a[2])
n
print(""" dhfldskfjhkf
fvdsfhdsjkfsd
jhgfjdsfhsdjfcn
jfbdsjfhdasjf'
 """)
 dhfldskfjhkf
fvdsfhdsjkfsd
jhgfjdsfhsdjfcn
jfbdsjfhdasjf'
 
a = 'vinaykumar'      # n-1
print(a[0:5]) 
vinay
print(a[0:5:3])
va
 print(a[:])
vinaykumar
print(a[4:7])
yku
ord('f')
102
chr(103)
'g'
#  online class string
predefined functions or in built functions
​
# 
a = 'data science'
a.capitalize()
'Data science'
 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 a.count()

TypeError: count() takes at least 1 argument (0 given)

pre defined function
# capitalize 
# count 
# endswith
# isalnum
# isalpha
# isdecimal
# isdigit
# islower
# isupper
# upper 
# title
# replace
# startswith
# swapcase
# 
a = 'swetha'
a.capitalize()
'Swetha'
​
a = 'vinay'
a.count('i')
1
​
a = 'siva'
a.startswith('s')
True
a = 'vinay'
a. endswith('y')
True
a = '324322'
a.count('2')
3
a = 'raja'
a.isalpha()
True
a = "vinay123"
a.isalpha()
False
a = '576756'
a.isdigit()
True
# no space should taken in middle
a = 'ramesh'
a.isalnum()
True
a = 'siva'
a.isalnum()
True
a = 'raMESH'
a.lower()
'ramesh'
a = 'rakHi'
a.upper()
'RAKHI'
a = 'swapna'
a.isupper()
False
a = 'raVi'
a.isupper()
False
a = 'i am viany and my age is 25'
a.title()
'I Am Viany And My Age Is 25'
# replace
d = 'i am learning machine learning and data learning'
d.replace('and','viany')
'i am learning machine learning viany data learning'
# formating technique
​
d = 'this is viany'
print('this is {}'.format('viany'))
this is viany
print('i am learning {a}','and {b}') .format(a= 'vinay',b= 'siva')
i am learning {a} and {b}
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 print('i am learning {a}','and {b}') .format(a= 'vinay',b= 'siva')

AttributeError: 'NoneType' object has no attribute 'format'

print('i am learning {s}'.format(s,'siva'))
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 print('i am learning {s}'.format(s,'siva'))

NameError: name 's' is not defined

print('siva and viany are {}'.format('bestfriends'))
siva and viany are bestfriends
# using ,
a= 'vinay'
b ='siva'
c = 'kiran'
print(a,b,c,'are friends')
vinay siva kiran are friends
list
# list is mutable data strctures
# it is denoted with -[]
# it will accept any data type 
# if a string is in the () we cant change but if a string is in the [] we can change
a =[12,13.4,'datascience']
print(a)
[12, 13.4, 'datascience']
type(a)
list
for i in a:
    print(i)
    print(type(i))
  
12
<class 'int'>
13.4
<class 'float'>
datascience
<class 'str'>
a = 'rwvo'
(a)
'rwvo'
## index and slicing 
b = [12,232,'siva','rabo','kamal']
(b[3])
'rabo'
a = ['vinay',12,12.5]
a.append(5)
(a)
['vinay', 12, 12.5, 5]
a = ['siva',12232,34.5,'4356']
a.clear()
(a)
[]
a = [841,3.71,'sivasankar']
b=a.copy()
(a)
[841, 3.71, 'sivasankar']
a =[1,13,34,'datascience',1,1]
a.count(1)
​
3
a = ['dbsadb',12,12.5,'vinay']
b = [11,'dfaef',23.4]
a.extend(b)
(a)
['dbsadb', 12, 12.5, 'vinay', 11, 'dfaef', 23.4]
a = ['gdfhfhg',12,12.5,"dgffsrf"]
a.index(12)
​
​
1
a = ['dfwf',12,34.5]
a.insert(1,55)
(a)
['dfwf', 55, 12, 34.5]
a = ['dfds',33,33.5,]
a.pop()
(a)
['dfds', 33]
a = ['siva','rajitha',78,78.8]
a.pop(1)
'rajitha'
a = ['begum','divya',33,]
a.remove(33)
(a)
['begum', 'divya']
a = ['divya',33,89.0]
a.reverse()
(a)
[89.0, 33, 'divya']
a = [44,12,33.5]
a.sort()
(a)
[12, 33.5, 44]
​
  Input In [80]
    a.sort('reverse' = true)
           ^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?


a = ['siva',23,44.5]
a.index(23)
​
1
a = ['dbfj',44,66.7]
a.pop()
66.7
a.pop()
44
a = ['rgterfe','rtewrew','hgfhfh',]
​
a.pop(1)
'rtewrew'
tuple
# tuple
a = (10)
(type(a))
int
a = (10,)
(type(a))
tuple
a = (4,10,13,'siva','ravi',12.4)
(a[1])
10
a = (12,[12,32],'vinay','siva')
(a[1][1])
32
# tuple is mutable
a = ('vinay','siva',23,45.5)
a[1]='rama'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [12], in <cell line: 2>()
      1 a = ('vinay','siva',23,45.5)
----> 2 a[1]='rama'

TypeError: 'tuple' object does not support item assignment

# packing and packing content
a = ('vinay','degreee',2022)
(name,study,lunch)  = a
(name)
'vinay'
(lunch)
2022
a= (23,'vinay','dogs')
(age,siva,divya) = a
(siva)
'vinay'
# operators
a =( 2,3,4)
b = (12.5,34)
(a+b)
(2, 3, 4, 12.5, 34)
a = (45,5)
b = a*6
(b)
​
(45, 5, 45, 5, 45, 5, 45, 5, 45, 5, 45, 5)
# member ship function
a = (1,44,'python')
(13 in a)
False
(1 in a)
True
a = (1,23,43,54,65)
for i in a:
    print(i)
    (i)
    
1
23
43
54
65
# built in functions
​
a = (23,'siva')
a.index(23)
0
a.count('siva')
1
len(a)
2
a = (12,44,544,67,67666,66)
max(a)
67666
min(a)
12
len(a)
6
a = 23,45,76b 
max(a)
76
len(a)
3
#sort
a =(34,23,45,65,12)
sorted(a)
[12, 23, 34, 45, 65]
## string concept split
a = 'vinay is studying inabroad'
a.split()
['vinay', 'is', 'studying', 'inabroad']
join
a = 'dogs eat cat'
b = a.split()
(b)
​
['dogs', 'eat', 'cat']
d = ' '.join(b)
a = 'i am happy'
b =a.split()
d = ' '.join(b)
(d)
​
'i am happy'
# stirngs
a = '1,2,3,4,5'
(a)
'1,2,3,4,5'
(type(a))
str
(a[0:2])
'1,'
# rough list 
a = [1,2,34,5,6,6]
a[0]=34
(a)
​
[34, 2, 34, 5, 6, 6]
a = [('siva'),45,78,98,1]
a[0]=19
(a)
      
[19, 45, 78, 98, 1]
(a[0])
19
max(a)
98
len(a)
5
sum(a)
241
a =[1,2,4,2]
a.append(88)
(a)
[1, 2, 4, 2, 88]
a =[1,2,3,4,5,6]
a.insert(2,3)
(a)
[1, 2, 3, 3, 4, 5, 6]
a.extend([12,100])
(a)
[1, 2, 3, 3, 4, 5, 6, 12, 100, 12, 100]
a = [12,34,56,788]
a.extend([10,100])
(a)
[12, 34, 56, 788, 10, 100]
a= 'pinky'
(a)
'pinky'
a = [1,2,3,4,5]
b = [0,9,8,7,6]
c = a+b
(c)
[1, 2, 3, 4, 5, 0, 9, 8, 7, 6]
a = [1,'siva','pinky']
del a[1]
(a)
[1, 'pinky']
a = [1,'siva','pinky']
a.remove(1)
(a)
['siva', 'pinky']
a = [1,'siva','pinky']
a.pop()
'pinky'
a = [1,'siva','pinky']
a.pop(1)
'siva'
a = [1,'siva','pinky']
a.clear()
(a)
[]
a = 'siva',89
b=list(a)
(b)
['siva', 89]
a = [1,4,5,6,3,54,88]
(sorted(a))
[1, 3, 4, 5, 6, 54, 88]
a = [1,4,5,6,3,54,88]
a.sort(reverse=True)
print(a)
[88, 54, 6, 5, 4, 3, 1]
# index and count and remove we use what is there in the index
a = [1,4,5,6,3,54,88]
a.reverse()
(a)
[88, 54, 3, 6, 5, 4, 1]
 # tuple
a = 1,2,3,4
(type(a))
tuple
a = 1,2,3,(12,34),[12,34]
(type(a))
tuple
a = (1,2,3,(12,34),[34,65],'stirng')
(a[0])
1
(a[3])
(12, 34)
​
(a[0])
1
a = 'viany'
(a[1])
'i'
a = 12,34,453,32,2,3,2,34,2,3
a.index(34)
1
)
#  split
a = 'i am a goood boy'
print(a.split())
['i', 'am', 'a', 'goood', 'boy']
b = 'kgf is rocky bhai world'
b.split()
['kgf', 'is', 'rocky', 'bhai', 'world']
b
[''.join(b)]
['kgf is rocky bhai world']
a = 'my name is vinay'
a.split()
['my', 'name', 'is', 'vinay']
[''.join(a)]
['my name is vinay']
a = 'i am a good boy in the class '
a.split()
['i', 'am', 'a', 'good', 'boy', 'in', 'the', 'class']
a
[''.join(a)]
['i am a good boy in the class ']
a = 'vinay'
a.capitalize()
'Vinay'
a.casefold()
'vinay'
i
a.count('i')
2
a = 'i am big fan of rocky'
a.title()
'I Am Big Fan Of Rocky'
a.replace('am','we')
'i we big fan of rocky'
for i in range(1,23):
    print(i)
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
a = 'datascience'
for i in a:
    print(i)
d
a
t
a
s
c
i
e
n
c
e
​

SyntaxError: invalid syntax (1766652940.py, line 1)

In [50]:
a = 'vinay'
for i in a:
    print(i)

v
i
n
a
y


In [51]:
a = 'vinay'
a.swapcase()

'VINAY'

In [52]:
a = 'vinay'
a.upper()

'VINAY'

In [60]:
a = ( ' i am a good {}'.format('boy'))
(a)

' i am a good boy'

In [62]:
a = 'ravi.vinay.siva.kumar'
a.split('.')

['ravi', 'vinay', 'siva', 'kumar']

In [63]:
a.split('.',2)

['ravi', 'vinay', 'siva.kumar']

In [66]:
a = 'vinay'
b  = 'siva'
c = a + b
(c)

'vinaysiva'

In [67]:
a = ['vinay','siva','ravi']
a.pop()

'ravi'

In [75]:
a = ['vinay','ravi','siva']
a.pop(1)
print(a)

['vinay', 'siva']


In [77]:
a = [1,3,6,342,264,1,3,45,77]
a.sort()
(a)

[1, 1, 3, 3, 6, 45, 77, 264, 342]

In [80]:
a.sort(reverse=True)
(a)

[342, 264, 77, 45, 6, 3, 3, 1, 1]

In [83]:
a = [1,2,34,4]
del a[1]
(a)

[1, 34, 4]

In [84]:
a = [1,2,3,4]
b = [9,8,7,6]
a +b

[1, 2, 3, 4, 9, 8, 7, 6]

In [86]:
a.extend(b)
(a)

[1, 2, 3, 4, 9, 8, 7, 6, 9, 8, 7, 6]

In [87]:
a = 4,[12,34],'vinay'
(type(a))

tuple

In [89]:
a = 'vinay',24,'data'
name,age,work = a

print(name)


vinay


In [91]:
a = 1,23,45,12,64,11
sorted(a)

[1, 11, 12, 23, 45, 64]

In [103]:
a = 1,23,45,12,64,11
(i in a)
(1 in a)

True

In [106]:
a = 'vinay','siva',23,43,56.6
for i in a:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'int'>
<class 'int'>
<class 'float'>


In [108]:
a = {1,23,2,23,(89,90)}
(a)

{(89, 90), 1, 2, 23}

In [110]:
a = {1,2,3,4}
a.add(56)
(a)

{1, 2, 3, 4, 56}

In [116]:
a = {1,2,3,42,32,3424,35,34,}
a.update([89,98])
(a)

{1, 2, 3, 32, 34, 35, 42, 89, 98, 3424}

In [118]:
a = {1,2,3,4,5,4.5}
(a)

{1, 2, 3, 4, 4.5, 5}

In [120]:
a = {1,2,3,4,5,4.5}
a.discard(5)
(a)

{1, 2, 3, 4, 4.5}

In [125]:
a = {1,2,3,4,5,4.5}
a.pop()
(a)

{2, 3, 4, 4.5, 5}

In [128]:
a = {1,2,3,4,5,4.5}
b = {7,8,9,0,6,7,7}
a.union(b)

{0, 1, 2, 3, 4, 4.5, 5, 6, 7, 8, 9}

In [129]:
a | b

{0, 1, 2, 3, 4, 4.5, 5, 6, 7, 8, 9}

In [130]:
a&b

set()

In [131]:
a = {1:'vinay'}
(type(a))

dict

In [132]:
books ={}
books['english']=12
books['social']=34
(books)

{'english': 12, 'social': 34}

In [135]:
a = {12,34,56}
a.update([99,43])
(a)

{12, 34, 43, 56, 99}

In [141]:
a = {1:'vinay',2:'ravi',3:'siva'}
a[1]

'vinay'

In [142]:
a.get(1)

'vinay'

In [143]:
a.get(2)

'ravi'

In [144]:
a = {1:'vinay',2:'siva',3:'ravi'}
for i in a:
    print("key =",i)

key = 1
key = 2
key = 3


In [146]:
for i in a:
    print('values =',i)
    print(a[i])

values = 1
vinay
values = 2
siva
values = 3
ravi


In [149]:
a = {1:'vinay',2:'siva',3:'ravi'}
for i in a:
    print('key =',i)

key = 1
key = 2
key = 3


In [152]:
a = {1:'vinay',2:'siva',3:'ravi'}
for i in a:
    print(a[i])

vinay
siva
ravi


In [156]:
a = {1:'vinay',2:'siva',3:'ravi'}
for i in a:
    print(i)

1
2
3


In [157]:
a = {1:'vinay',2:'siva',3:'ravi'}
for i in a.keys():
    print(i)

1
2
3


In [158]:
for i in a.values():
    print(i)

vinay
siva
ravi


In [160]:
a = {1:'vinay',2:'siva',3:'ravi'}
for i in a.items():
    print(i)

(1, 'vinay')
(2, 'siva')
(3, 'ravi')


In [12]:
list1 = [6,23,3,2,0,9,8,75]
(list1[:][1])

23

In [25]:
a = [6,23,3,2,0,9,8,75]
print(a[1:8:2])

[23, 2, 9, 75]


In [5]:
def vinay(a):
    if a%2==0:
        print("EVEN")
    else:
            print("ODD")
            

In [6]:
vinay(66)

EVEN


In [ ]:
# return concept in functiolns
a = int(input('enter a value'))


In [ ]:
c= []
for i in  range(10):
    a= int(input())
    c.append(a)
   

In [17]:
a = 11
if a%1 == 0:
    print('prime')

prime


In [41]:
a = 10
k = []
for i in range(1,a+1):
    if a%i == 0:
        k.append(i)
        
print(k)
print()



c = 0

for j in k:
    c = c+j
    
    
    
if c == a:
    print('it is a prime number')
else:
    print('not a prime number')
    
    
        
        
        

[1, 2, 5, 10]

not a prime number


In [6]:
k = [1,2,3]
for i in k:
    print(i)

1
2
3


In [10]:
a = 10
f = []
for i in range(1,a+1):
    if a %i == 0:
        f.append(i)
print(f)
print()



[1, 2, 5, 10]


In [11]:
a = 13
for i in range(1,a+1):
    if a%i==0:
        print(i)

1
13


In [18]:
a = 14
b = []
for i in range(1,a+1):
    if a%i==0:
        b.append(i)
print(b)
        

[1, 2, 7, 14]


In [19]:
a = 13

if a%2==0:
    print('even')
else:
    print('odd')

odd


In [21]:
a = 12
for i in range(1,a+1):
    if a%i==0:
        

1
2
3
4
6
12


In [22]:
# lamda function is an anonymous function


In [24]:
a= 1
b = 3

vinay =lambda x,y: x+y
(vinay(a,b))

4

In [25]:
a = 12
b = 34

c  = lambda x,y:x*y
(c(a,b))

408

In [29]:
a =23

k = lambda x:x>4
(k(a))

True

In [ ]:
a =12 

c = lambda x:x%2==0

(c(a))

In [ ]:
a = int (input('enter a number '))
for i  in range(1,11):
    print(a,'*',i,'=',a,i)